spring.application.name=url-shortner

# --- PostgreSQL Database Configuration ---
spring.datasource.url=jdbc:postgresql://localhost:5432/kishore?currentSchema=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Hibernate JPA Configuration ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Options: validate | update | create | create-drop
spring.jpa.hibernate.ddl-auto=update
# Enable SQL logging
spring.jpa.show-sql=true


# Set default schema for Hibernate
spring.jpa.properties.hibernate.default_schema=application

# --- Connection Pool Settings (Optional, for optimization) ---
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000


